services:
  trioverse-web:
    build: .
    container_name: trioverse-app
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - trioverse-network

networks:
  trioverse-network:
    external: true